apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: default
spec:
  preemption:
    reclaimWithinCohort: Any
    borrowWithinCohort:
      policy: LowerPriority
      maxPriorityThreshold: 100
    withinClusterQueue: LowerPriority
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: agent
  queueingStrategy: BestEffortFIFO
  cohortName: gpu-cohort
  resourceGroups:
  - coveredResources:
    - cpu
    - memory
    flavors:
    - name: default-flavor
      resources:
      - name: cpu
        nominalQuota: 50
      - name: memory
        nominalQuota: 50Gi
  - coveredResources:
    - nvidia.com/gpu
    flavors:
    - name: gpu-flavor
      resources:
      - name: nvidia.com/gpu
        nominalQuota: "3"
        borrowingLimit: "1"
